[Application Options]
alias=agent-bitcoin
debuglevel=info
maxpendingchannels=5

# === Fast Regtest Startup ===
sync-freelist=1
ignore-historical-gossip-filters=1
gc-canceled-invoices-on-startup=1
gc-canceled-invoices-on-the-fly=1

bitcoin.active=1
bitcoin.regtest=1
bitcoin.node=bitcoind

[Bitcoind]
bitcoind.rpchost=bitcoind:18443
bitcoind.rpcuser=btc
bitcoind.rpcpass=btc
bitcoind.zmqpubrawblock=tcp://bitcoind:28332
bitcoind.zmqpubrawtx=tcp://bitcoind:28333

[Routing]
routing.assumechanvalid=1
