#!/usr/bin/env python3
"""Write a one-page demo PDF to stdout.

The L402 origin launches this script for GET /paid/script.pdf after Aperture
has accepted payment. Stdlib only; no network, no LND.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# Same directory as origin.py (Docker WORKDIR /app, or repo l402/).
sys.path.insert(0, str(Path(__file__).resolve().parent))
from origin import _simple_pdf  # noqa: E402


def pdf_bytes(network: str) -> bytes:
    return _simple_pdf(
        [
            "agent-bitcoin L402 script PDF",
            "",
            f"network: {network}",
            "This file was generated by l402/generate_script_pdf.py.",
            "The origin launched this script after an L402 payment.",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Emit a demo PDF on stdout")
    parser.add_argument(
        "--network",
        default=(os.environ.get("L402_NETWORK") or "regtest").strip() or "regtest",
    )
    args = parser.parse_args()
    sys.stdout.buffer.write(pdf_bytes(args.network))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
