"""Tiny HTTP origin for the Aperture L402 PoC (no LND, no payments)."""

from __future__ import annotations

import json
import os
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


def _simple_pdf(lines: list[str]) -> bytes:
    """Minimal PDF 1.4 with Helvetica text (no third-party libs)."""

    def esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    cmds = ["BT", "/F1 14 Tf", "72 720 Td"]
    for i, line in enumerate(lines):
        if i:
            cmds.append("0 -20 Td")
        cmds.append(f"({esc(line)}) Tj")
    cmds.append("ET")
    stream = ("\n".join(cmds) + "\n").encode("latin-1", errors="replace")

    bodies = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
        ),
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, body in enumerate(bodies, start=1):
        offsets.append(len(out))
        out.extend(b"%d 0 obj\n" % i)
        out.extend(body)
        out.extend(b"\nendobj\n")
    xref_pos = len(out)
    out.extend(b"xref\n0 %d\n" % (len(bodies) + 1))
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(b"%010d 00000 n \n" % off)
    out.extend(
        b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
        % (len(bodies) + 1, xref_pos)
    )
    return bytes(out)


def demo_pdf_bytes(network: str) -> bytes:
    return _simple_pdf(
        [
            "agent-bitcoin L402 demo report",
            "",
            f"network: {network}",
            "This PDF is generated by l402/origin.py.",
            "If you can read this, the paid file download worked.",
        ]
    )


def _payload(path: str) -> tuple[int, dict]:
    """JSON routes used by existing unit tests."""
    network = os.environ.get("L402_NETWORK", "regtest").strip() or "regtest"
    route = path.split("?", 1)[0]
    if route == "/health":
        return 200, {"ok": True, "service": "l402-demo"}
    if route == "/paid/hello":
        return 200, {
            "ok": True,
            "service": "l402-demo",
            "network": network,
            "msg": "hello",
        }
    return 404, {"ok": False, "error": "not found"}


def dispatch(path: str) -> tuple[int, str, bytes]:
    """status, Content-Type, body."""
    network = os.environ.get("L402_NETWORK", "regtest").strip() or "regtest"
    route = path.split("?", 1)[0]
    if route == "/paid/report.pdf":
        return 200, "application/pdf", demo_pdf_bytes(network)
    status, obj = _payload(path)
    return status, "application/json", json.dumps(obj).encode("utf-8")


class OriginHandler(BaseHTTPRequestHandler):
    def do_GET(self) -> None:  # noqa: N802
        status, content_type, raw = dispatch(self.path)
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        if content_type == "application/pdf":
            self.send_header(
                "Content-Disposition", 'attachment; filename="l402-demo-report.pdf"'
            )
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def log_message(self, fmt: str, *args: object) -> None:
        sys_stderr = __import__("sys").stderr
        sys_stderr.write("%s - %s\n" % (self.address_string(), fmt % args))


def main() -> None:
    host = os.environ.get("L402_ORIGIN_HOST", "0.0.0.0")
    port = int(os.environ.get("L402_ORIGIN_PORT", "8090"))
    httpd = ThreadingHTTPServer((host, port), OriginHandler)
    print(f"l402 origin listening on {host}:{port}", flush=True)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
