"""Tiny HTTP origin for the Aperture L402 PoC (no LND, no payments)."""

from __future__ import annotations

import json
import os
import struct
import subprocess
import sys
import zlib
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

_SCRIPT_PDF = Path(__file__).resolve().parent / "generate_script_pdf.py"

try:
    from l402 import mempool_feerate as _mempool_feerate
    from l402 import mempool_backlog as _mempool_backlog
    from l402 import fee_for_vsize as _fee_for_vsize
    from l402 import confirm_target as _confirm_target
    from l402 import btc_usd as _btc_usd
    from l402 import ln_path_fee_hint as _ln_path_fee_hint
    from l402 import ln_invoice_decode as _ln_invoice_decode
    from l402 import ln_invoice_preflight as _ln_invoice_preflight
    from l402 import nostr_event_verify as _nostr_event_verify
    from l402 import nostr_npub_decode as _nostr_npub_decode
    from l402 import nostr_zap_receipt_inspect as _nostr_zap_receipt_inspect
except ImportError:  # Docker WORKDIR /app
    import mempool_feerate as _mempool_feerate  # type: ignore[no-redef]
    import mempool_backlog as _mempool_backlog  # type: ignore[no-redef]
    import fee_for_vsize as _fee_for_vsize  # type: ignore[no-redef]
    import confirm_target as _confirm_target  # type: ignore[no-redef]
    import btc_usd as _btc_usd  # type: ignore[no-redef]
    import ln_path_fee_hint as _ln_path_fee_hint  # type: ignore[no-redef]
    import ln_invoice_decode as _ln_invoice_decode  # type: ignore[no-redef]
    import ln_invoice_preflight as _ln_invoice_preflight  # type: ignore[no-redef]
    import nostr_event_verify as _nostr_event_verify  # type: ignore[no-redef]
    import nostr_npub_decode as _nostr_npub_decode  # type: ignore[no-redef]
    import nostr_zap_receipt_inspect as _nostr_zap_receipt_inspect  # type: ignore[no-redef]


def _simple_pdf(lines: list[str]) -> bytes:
    """Minimal PDF 1.4 with Helvetica text (no third-party libs)."""

    def esc(s: str) -> str:
        return s.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")

    cmds = ["BT", "/F1 14 Tf", "72 720 Td"]
    for i, line in enumerate(lines):
        if i:
            cmds.append("0 -20 Td")
        cmds.append(f"({esc(line)}) Tj")
    cmds.append("ET")
    stream = ("\n".join(cmds) + "\n").encode("latin-1", errors="replace")

    bodies = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        (
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] "
            b"/Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>"
        ),
        b"<< /Length %d >>\nstream\n" % len(stream) + stream + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for i, body in enumerate(bodies, start=1):
        offsets.append(len(out))
        out.extend(b"%d 0 obj\n" % i)
        out.extend(body)
        out.extend(b"\nendobj\n")
    xref_pos = len(out)
    out.extend(b"xref\n0 %d\n" % (len(bodies) + 1))
    out.extend(b"0000000000 65535 f \n")
    for off in offsets[1:]:
        out.extend(b"%010d 00000 n \n" % off)
    out.extend(
        b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n"
        % (len(bodies) + 1, xref_pos)
    )
    return bytes(out)


def demo_pdf_bytes(network: str) -> bytes:
    return _simple_pdf(
        [
            "agent-bitcoin L402 demo report",
            "",
            f"network: {network}",
            "This PDF is generated by l402/origin.py.",
            "If you can read this, the paid file download worked.",
        ]
    )


# 5x7 glyphs, bit 4 = leftmost pixel. Enough for the badge caption.
_GLYPHS: dict[str, tuple[int, ...]] = {
    " ": (0, 0, 0, 0, 0, 0, 0),
    "-": (0, 0, 0, 0b01110, 0, 0, 0),
    ":": (0, 0, 0b00100, 0, 0b00100, 0, 0),
    "0": (0b01110, 0b10001, 0b10011, 0b10101, 0b11001, 0b10001, 0b01110),
    "1": (0b00100, 0b01100, 0b00100, 0b00100, 0b00100, 0b00100, 0b01110),
    "2": (0b01110, 0b10001, 0b00001, 0b00010, 0b00100, 0b01000, 0b11111),
    "3": (0b11110, 0b00001, 0b00001, 0b01110, 0b00001, 0b00001, 0b11110),
    "4": (0b00010, 0b00110, 0b01010, 0b10010, 0b11111, 0b00010, 0b00010),
    "5": (0b11111, 0b10000, 0b11110, 0b00001, 0b00001, 0b10001, 0b01110),
    "6": (0b01110, 0b10000, 0b10000, 0b11110, 0b10001, 0b10001, 0b01110),
    "7": (0b11111, 0b00001, 0b00010, 0b00100, 0b01000, 0b01000, 0b01000),
    "8": (0b01110, 0b10001, 0b10001, 0b01110, 0b10001, 0b10001, 0b01110),
    "9": (0b01110, 0b10001, 0b10001, 0b01111, 0b00001, 0b00001, 0b01110),
    "A": (0b01110, 0b10001, 0b10001, 0b11111, 0b10001, 0b10001, 0b10001),
    "B": (0b11110, 0b10001, 0b10001, 0b11110, 0b10001, 0b10001, 0b11110),
    "C": (0b01110, 0b10001, 0b10000, 0b10000, 0b10000, 0b10001, 0b01110),
    "D": (0b11110, 0b10001, 0b10001, 0b10001, 0b10001, 0b10001, 0b11110),
    "E": (0b11111, 0b10000, 0b10000, 0b11110, 0b10000, 0b10000, 0b11111),
    "F": (0b11111, 0b10000, 0b10000, 0b11110, 0b10000, 0b10000, 0b10000),
    "G": (0b01110, 0b10001, 0b10000, 0b10111, 0b10001, 0b10001, 0b01110),
    "H": (0b10001, 0b10001, 0b10001, 0b11111, 0b10001, 0b10001, 0b10001),
    "I": (0b01110, 0b00100, 0b00100, 0b00100, 0b00100, 0b00100, 0b01110),
    "K": (0b10001, 0b10010, 0b10100, 0b11000, 0b10100, 0b10010, 0b10001),
    "L": (0b10000, 0b10000, 0b10000, 0b10000, 0b10000, 0b10000, 0b11111),
    "M": (0b10001, 0b11011, 0b10101, 0b10001, 0b10001, 0b10001, 0b10001),
    "N": (0b10001, 0b11001, 0b10101, 0b10011, 0b10001, 0b10001, 0b10001),
    "O": (0b01110, 0b10001, 0b10001, 0b10001, 0b10001, 0b10001, 0b01110),
    "P": (0b11110, 0b10001, 0b10001, 0b11110, 0b10000, 0b10000, 0b10000),
    "R": (0b11110, 0b10001, 0b10001, 0b11110, 0b10100, 0b10010, 0b10001),
    "S": (0b01111, 0b10000, 0b10000, 0b01110, 0b00001, 0b00001, 0b11110),
    "T": (0b11111, 0b00100, 0b00100, 0b00100, 0b00100, 0b00100, 0b00100),
    "W": (0b10001, 0b10001, 0b10001, 0b10001, 0b10101, 0b11011, 0b10001),
}


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    crc = zlib.crc32(tag + data) & 0xFFFFFFFF
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", crc)


def _rgb_png(width: int, height: int, pixels: bytearray) -> bytes:
    raw = bytearray()
    row = width * 3
    for y in range(height):
        raw.append(0)
        raw.extend(pixels[y * row : (y + 1) * row])
    ihdr = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return (
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", ihdr)
        + _png_chunk(b"IDAT", zlib.compress(bytes(raw), 9))
        + _png_chunk(b"IEND", b"")
    )


def _fill(
    pixels: bytearray, width: int, x0: int, y0: int, x1: int, y1: int, rgb: bytes
) -> None:
    for y in range(y0, y1):
        start = (y * width + x0) * 3
        end = (y * width + x1) * 3
        pixels[start:end] = rgb * (x1 - x0)


def _draw_text(
    pixels: bytearray,
    width: int,
    height: int,
    x: int,
    y: int,
    text: str,
    rgb: bytes,
    scale: int,
) -> None:
    for ch in text.upper():
        glyph = _GLYPHS.get(ch, _GLYPHS[" "])
        for row, bits in enumerate(glyph):
            for col in range(5):
                if not bits & (1 << (4 - col)):
                    continue
                px0 = x + col * scale
                py0 = y + row * scale
                for dy in range(scale):
                    py = py0 + dy
                    if py < 0 or py >= height:
                        continue
                    for dx in range(scale):
                        px = px0 + dx
                        if 0 <= px < width:
                            i = (py * width + px) * 3
                            pixels[i : i + 3] = rgb
        x += 6 * scale


def demo_png_bytes(network: str) -> bytes:
    """Readable badge: gold bar + L402 PAID + network name. No third-party libs."""
    width, height = 560, 200
    pixels = bytearray(b"\x1a\x1a\x2e" * (width * height))
    _fill(pixels, width, 0, 0, 16, height, b"\xe8\xb8\x6d")
    _draw_text(pixels, width, height, 36, 28, "L402 PAID", b"\xe8\xb8\x6d", 6)
    _draw_text(pixels, width, height, 36, 86, "agent-bitcoin", b"\xf0\xf0\xf0", 4)
    _draw_text(
        pixels, width, height, 36, 140, f"network: {network}", b"\xb0\xb0\xc0", 3
    )
    return _rgb_png(width, height, pixels)


def _payload(path: str) -> tuple[int, dict]:
    """JSON routes used by existing unit tests."""
    network = os.environ.get("L402_NETWORK", "regtest").strip() or "regtest"
    route = path.split("?", 1)[0]
    if route == "/health":
        return 200, {"ok": True, "service": "l402-demo"}
    if route == "/paid/hello":
        return 200, {
            "ok": True,
            "service": "l402-demo",
            "network": network,
            "msg": "hello",
        }
    return 404, {"ok": False, "error": "not found"}


def script_pdf_bytes(network: str) -> bytes:
    """Launch generate_script_pdf.py; PDF is on stdout."""
    proc = subprocess.run(
        [sys.executable, str(_SCRIPT_PDF), "--network", network],
        capture_output=True,
        timeout=10,
        check=False,
    )
    if proc.returncode != 0 or not proc.stdout.startswith(b"%PDF"):
        err = proc.stderr.decode("utf-8", errors="replace").strip()
        raise RuntimeError(err or "generate_script_pdf.py failed")
    return proc.stdout


def dispatch(
    path: str, method: str = "GET", body: bytes = b""
) -> tuple[int, str, bytes]:
    """status, Content-Type, body."""
    network = os.environ.get("L402_NETWORK", "regtest").strip() or "regtest"
    route = path.split("?", 1)[0]
    verb = (method or "GET").upper()
    if route == "/paid/finance/mempool-feerate":
        try:
            payload = _mempool_feerate.get_quote()
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _mempool_feerate.UpstreamUnavailable:
            err = {"ok": False, "error": "upstream_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/mempool-backlog":
        try:
            payload = _mempool_backlog.get_quote()
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _mempool_backlog.UpstreamUnavailable:
            err = {"ok": False, "error": "upstream_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/fee-for-vsize":
        try:
            payload = _fee_for_vsize.quote_for_request(path)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _fee_for_vsize.BadVsize:
            err = {"ok": False, "error": "bad_vsize"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _mempool_feerate.UpstreamUnavailable:
            err = {"ok": False, "error": "upstream_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/confirm-target":
        try:
            payload = _confirm_target.quote_for_request(path)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _fee_for_vsize.BadVsize:
            err = {"ok": False, "error": "bad_vsize"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _confirm_target.BadConfirmTarget:
            err = {"ok": False, "error": "bad_confirm_target"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _mempool_feerate.UpstreamUnavailable:
            err = {"ok": False, "error": "upstream_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/btc-usd":
        try:
            payload = _btc_usd.get_quote()
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _btc_usd.UpstreamUnavailable:
            err = {"ok": False, "error": "upstream_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/ln-path-fee-hint":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _ln_path_fee_hint.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _ln_path_fee_hint.BadInput:
            err = {"ok": False, "error": "bad_input"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _ln_path_fee_hint.NoRoute:
            err = {"ok": False, "error": "no_route"}
            return 404, "application/json", json.dumps(err).encode("utf-8")
        except _ln_path_fee_hint.LndUnavailable:
            err = {"ok": False, "error": "lnd_unavailable"}
            return 503, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/ln-invoice-decode":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _ln_invoice_decode.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _ln_invoice_decode.BadInvoice:
            err = {"ok": False, "error": "bad_invoice"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/finance/ln-invoice-preflight":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _ln_invoice_preflight.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _ln_invoice_preflight.MissingBolt11:
            err = {"ok": False, "error": "missing_bolt11"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _ln_invoice_preflight.BadMaxSats:
            err = {"ok": False, "error": "bad_max_sats"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _ln_invoice_preflight.BadNetwork:
            err = {"ok": False, "error": "bad_network"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
        except _ln_invoice_preflight.BadInput:
            err = {"ok": False, "error": "bad_input"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/nostr/event-verify":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _nostr_event_verify.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _nostr_event_verify.MissingEvent:
            err = {"ok": False, "error": "missing_event"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/nostr/npub-decode":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _nostr_npub_decode.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _nostr_npub_decode.MissingEntity:
            err = {"ok": False, "error": "missing_entity"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/nostr/zap-receipt-inspect":
        if verb != "POST":
            err = {"ok": False, "error": "method_not_allowed"}
            return 405, "application/json", json.dumps(err).encode("utf-8")
        try:
            payload = _nostr_zap_receipt_inspect.handle_request(body)
            return 200, "application/json", json.dumps(payload).encode("utf-8")
        except _nostr_zap_receipt_inspect.MissingEvent:
            err = {"ok": False, "error": "missing_event"}
            return 400, "application/json", json.dumps(err).encode("utf-8")
    if route == "/paid/report.pdf":
        return 200, "application/pdf", demo_pdf_bytes(network)
    if route == "/paid/script.pdf":
        try:
            return 200, "application/pdf", script_pdf_bytes(network)
        except (OSError, RuntimeError, subprocess.TimeoutExpired):
            return 500, "text/plain", b"script pdf generation failed\n"
    if route == "/paid/badge.png":
        return 200, "image/png", demo_png_bytes(network)
    status, obj = _payload(path)
    return status, "application/json", json.dumps(obj).encode("utf-8")


class OriginHandler(BaseHTTPRequestHandler):
    def _send(self, status: int, content_type: str, raw: bytes) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        if content_type == "application/pdf":
            name = (
                "l402-script.pdf"
                if "script.pdf" in self.path.split("?", 1)[0]
                else "l402-demo-report.pdf"
            )
            self.send_header("Content-Disposition", f'attachment; filename="{name}"')
        elif content_type == "image/png":
            self.send_header(
                "Content-Disposition", 'attachment; filename="l402-demo-badge.png"'
            )
        self.send_header("Content-Length", str(len(raw)))
        self.end_headers()
        self.wfile.write(raw)

    def do_GET(self) -> None:  # noqa: N802
        status, content_type, raw = dispatch(self.path, method="GET")
        self._send(status, content_type, raw)

    def do_POST(self) -> None:  # noqa: N802
        try:
            length = int(self.headers.get("Content-Length") or "0")
        except ValueError:
            length = 0
        if length < 0:
            length = 0
        if length > 65_536:
            err = json.dumps({"ok": False, "error": "bad_input"}).encode("utf-8")
            self._send(400, "application/json", err)
            return
        raw_body = self.rfile.read(length) if length else b""
        status, content_type, raw = dispatch(self.path, method="POST", body=raw_body)
        self._send(status, content_type, raw)

    def log_message(self, fmt: str, *args: object) -> None:
        sys_stderr = __import__("sys").stderr
        sys_stderr.write("%s - %s\n" % (self.address_string(), fmt % args))


def main() -> None:
    host = os.environ.get("L402_ORIGIN_HOST", "0.0.0.0")
    port = int(os.environ.get("L402_ORIGIN_PORT", "8090"))
    httpd = ThreadingHTTPServer((host, port), OriginHandler)
    print(f"l402 origin listening on {host}:{port}", flush=True)
    httpd.serve_forever()


if __name__ == "__main__":
    main()
